### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rcookerly** [tsaklidis/subreddits#3]
Hi, I'm trying to use your tool to transfer all my subreddits from an old to new account. However, I'm having issues with it. Was hoping you could help me out. I followed your instructions but when I run the command, "python3 src/main.py -e" I am getting this error:

Traceback (most recent call last):
  File "src/main.py", line 5, in <module>
    import praw
ModuleNotFoundError: No module named 'praw'

Any chance you can help me?

**Comment by k3d3** [comment]
You missed the `pip install -r requirements.txt` line.

**Comment by rcookerly** [comment]
Pretty sure I did that but I'll give it another shot. Thanks so much!

**Comment by k3d3** [comment]
The other possibility is your pip install is for a different Python install (e.g. python2).

In that case, you can instead run `python3 -m pip install -r requrements.txt`

**Comment by rcookerly** [comment]
I see. Thanks for the tips! Will try again in the next day or two.

**Comment by minanagehsalalma** [comment]
> Will try again in the next day or two.

Last Commented : A year ago 🤣🤣

**Comment by rcookerly** [comment]
> > Will try again in the next day or two.
> 
> Last Commented : A year ago 🤣🤣

Lol ;)

**Comment by minanagehsalalma** [comment]
> > > Will try again in the next day or two.
> > 
> > 
> > Last Commented : A year ago 🤣🤣
> 
> Lol ;)

@rcookerly  So yeah did it work tho

**Comment by rcookerly** [comment]
> > > > Will try again in the next day or two.
> > > 
> > > 
> > > Last Commented : A year ago 🤣🤣
> > 
> > 
> > Lol ;)
> 
> @rcookerly So yeah did it work tho

Never did try it again. Was banned from Reddit for something stupid, so screw Reddit.

**Comment by minanagehsalalma** [comment]
> Never did try it again. Was banned from Reddit for something stupid, so screw Reddit.

@rcookerly lmao same, to hell it goes.

**Comment by rcookerly** [comment]
> > Never did try it again. Was banned from Reddit for something stupid, so screw Reddit.
> 
> @rcookerly lmao same, to hell it goes.

I used to love Reddit because it seemed like a true free-speech platform. It has become way too woke the last few years. First, it started with being banned on certain subreddits for ridiculous things, then was banned permanently from the platform. There was a video of a man beating his wife, so I commented that I would beat the shit out of him if I saw that in person, and...I was banned for threatening violence. Unreal. Fuck Reddit.

**Comment by minanagehsalalma** [comment]
> so I commented that I would beat the shit out of him if I saw that in person, and...I was banned for threatening violence. Unreal. Fuck Reddit.

Lol yeah... It's not just the administration

It's the users too are too  fucking entitled...

Mostly comments and posts don't get looked at unless reported

So that's on the users too.

I also got all types of ban

What bothers me the most
Is that not only they unjustifiable ban you

But also all your accounts on the platform

Like wtf i didn't break any rules with the other accounts

I use it for important purposes... But no

You do something on one account you get banned using a net trick called hardware id
That they associate with your accounts

The mods get to see it too i think.... That's how they detect ban evasion

Pro tip  :  use third-party reddit apps

They don't send that hardware id

Good luck mate, nice encounter :)

**Comment by rcookerly** [comment]
> > so I commented that I would beat the shit out of him if I saw that in person, and...I was banned for threatening violence. Unreal. Fuck Reddit.
> 
> Lol yeah... It's not just the administration
> 
> It's the users too are too fucking entitled...
> 
> Mostly comments and posts don't get looked at unless reported
> 
> So that's on the users too.
> 
> I also got all types of ban
> 
> What bothers me the most Is that not only they unjustifiable ban you
> 
> But also all your accounts on the platform
> 
> Like wtf i didn't break any rules with the other accounts
> 
> I use it for important purposes... But no
> 
> You do something on one account you get banned using a net trick called hardware id That they associate with your accounts
> 
> The mods get to see it too i think.... That's how they detect ban evasion
> 
> Pro tip : use third-party reddit apps
> 
> They don't send that hardware id
> 
> Good luck mate, nice encounter :)

Exactly! I had 4 accounts and ALL were banned...wtf! Did not know about third-party reddit apps, though! So if I made a new account on a third-party app right now, it won't automatically be banned?

**Comment by minanagehsalalma** [comment]
> So if I made a new account on a third-party app right now, it won't automatically be banned?

@rcookerly nope

But make sure to have the official app removed

And don't login to the old accounts again

As they use ips too

Restart the router so the ip changes too

That's it, you do be fine...

Apps that are good :  boost, sync, reddit is fun.

Good luck

**Comment by rcookerly** [comment]
Awesome! Thanks for the tip! Tried looking up boost and sync, but don't see any apps related to Reddit (I'm in the US). Apollo seems like a popular one here.

**Comment by minanagehsalalma** [comment]
> Awesome! Thanks for the tip! Tried looking up boost and sync, but don't see any apps related to Reddit (I'm in the US). Apollo seems like a popular one here.

@rcookerly Yeah apollo works great too

You should type the app name + reddit 

to find them tho

**Comment by rcookerly** [comment]
> > Awesome! Thanks for the tip! Tried looking up boost and sync, but don't see any apps related to Reddit (I'm in the US). Apollo seems like a popular one here.
> 
> @rcookerly Yeah apollo works great too
> 
> You should type the app name + reddit
> 
> to find them tho

Cool, thanks :) Nice chatting with you, take care!

**Comment by tsaklidis** [comment]
Don't forget to install the requirements for your installed version of python
`pip install -r requirements.txt` or `pip3 install -r requirements.txt`

Closing this as not an issue.
